import type { Architecture, ArchitectureNode } from '../types/architecture';

const SCALE_X = 1.65;
const SCALE_Y = 1.25;

const nodePositions: Record<string, { x: number; y: number }> = { 
  users: { x: 0, y: 230 }, 
  dns: { x: 310, y: 230 }, 
  cdn: { x: 620, y: 230 }, 
  gateway: { x: 930, y: 110 }, 
  balancer: { x: 1240, y: 110 }, 
  auth: { x: 1550, y: 0 }, 
  'payment-service': { x: 1550, y: 245 }, 
  fraud: { x: 1860, y: 105 }, 
  queue: { x: 1860, y: 350 }, 
  cache: { x: 1860, y: 595 }, 
  'primary-db': { x: 2170, y: 245 }, 
  replica: { x: 2480, y: 80 }, 
  'backup-db': { x: 2480, y: 450 }, 
  monitoring: { x: 1550, y: 500 } 
};

// Helper to get exact node coordinates matching ArchitectureCanvas
function getNodeCoords(node: ArchitectureNode, index: number) {
  let rawX = 0;
  let rawY = 0;
  
  if (node.metadata && typeof node.metadata.x === 'number' && typeof node.metadata.y === 'number') {
    rawX = node.metadata.x;
    rawY = node.metadata.y;
  } else if (nodePositions[node.id]) {
    rawX = nodePositions[node.id].x;
    rawY = nodePositions[node.id].y;
  } else {
    rawX = 80 + (index % 4) * 320;
    rawY = 120 + Math.floor(index / 4) * 220;
  }
  
  return {
    x: rawX * SCALE_X,
    y: rawY * SCALE_Y
  };
}

/**
 * Generates a clean JSON file representation of the architecture.
 */
export function exportAsJson(architecture: Architecture): string {
  return JSON.stringify(architecture, null, 2);
}

/**
 * Generates a beautiful System Design Specification in Markdown format (.md).
 */
export function exportAsMarkdown(architecture: Architecture): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  let markdown = `# System Design Specification: ${architecture.name}\n`;
  markdown += `> Generated by **SynthArchitecture** on ${dateStr}  \n`;
  markdown += `> **Deployment Target**: Production Container / Multi-Region Cloud Cluster\n\n`;

  markdown += `## 1. Executive Summary\n`;
  markdown += `${architecture.description}\n\n`;

  markdown += `## 2. Peak Traffic & Load Profiles\n`;
  const peakRps = Math.round(architecture.estimatedTraffic.requestsPerSecond * architecture.estimatedTraffic.peakMultiplier);
  markdown += `- **Baseline Load**: \`${architecture.estimatedTraffic.requestsPerSecond.toLocaleString()} RPS\` (Requests Per Second)\n`;
  markdown += `- **Peak Factor**: \`${architecture.estimatedTraffic.peakMultiplier}x\`\n`;
  markdown += `- **Design-Limit Peak Load**: \`${peakRps.toLocaleString()} RPS\`  \n`;
  markdown += `*The system services are scaled horizontally to sustain the designated peak factors with sufficient buffer margin.*\n\n`;

  markdown += `## 3. Core Topology Inventory\n`;
  markdown += `The architecture is provisioned with **${architecture.nodes.length} primary infrastructure components** arranged across logical boundaries:\n\n`;
  
  markdown += `| Node ID | Component Name | Service Type | Location / Region | Capacity | Current Load | Target Latency | Replicas | Status |\n`;
  markdown += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;

  architecture.nodes.forEach((node) => {
    const utilization = Math.round((node.currentLoad / Math.max(node.capacity, 1)) * 100);
    const statusEmoji = node.status === 'healthy' ? '🟢 Healthy' : node.status === 'failed' ? '🔴 FAILED' : '🟡 Degraded';
    markdown += `| \`${node.id}\` | **${node.name}** | \`${node.type}\` | ${node.region} | ${node.capacity.toLocaleString()} | ${node.currentLoad.toLocaleString()} (${utilization}%) | ${node.latencyMs}ms | ${node.replicas}x | ${statusEmoji} |\n`;
  });
  
  markdown += `\n\n## 4. Logical Routes & Protocol Matrix\n`;
  markdown += `These connection matrices define active client ingestion, load balancing, and backing synchronous data pipelines:\n\n`;

  markdown += `| Route ID | Source Component | Target Component | Active Load % | Nominal Latency | Transport Protocol | Route Role |\n`;
  markdown += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;

  architecture.edges.forEach((edge) => {
    const sourceNode = architecture.nodes.find(n => n.id === edge.source)?.name || edge.source;
    const targetNode = architecture.nodes.find(n => n.id === edge.target)?.name || edge.target;
    const role = edge.backup ? '🔮 Backup / Failover Fail-Safe' : '⚡ Primary Dynamic Ingress';
    const statusSymbol = edge.active ? '🟢 Active' : '⚪ Standby';
    markdown += `| \`${edge.id}\` | ${sourceNode} | ${targetNode} | ${edge.trafficPercentage}% (${statusSymbol}) | ${edge.latencyMs}ms | \`${edge.protocol}\` | ${role} |\n`;
  });

  markdown += `\n\n## 5. Architectural Assumptions & Guarantees\n`;
  architecture.assumptions.forEach((assumption, i) => {
    markdown += `${i + 1}. **${assumption}**\n`;
  });

  markdown += `\n## 6. Resilience Audit, Failure Modes & Risks\n`;
  markdown += `A structural resilience evaluation of the active topology highlights the following active engineering risks:\n\n`;
  architecture.risks.forEach((risk, i) => {
    markdown += `- 🚨 **Risk #${i + 1}**: ${risk}\n`;
  });

  markdown += `\n## 7. Optimization & Hardening Recommendations\n`;
  markdown += `Actionable next steps to patch vulnerabilities and improve systemic efficiency:\n\n`;
  architecture.recommendations.forEach((rec, i) => {
    markdown += `- 🛠️ **Priority Recommendation #${i + 1}**: ${rec}\n`;
  });

  markdown += `\n---\n*System specifications generated automatically. To update or re-evaluate performance boundaries, re-compile this topology with a fresh prompt query inside SynthArchitecture.*`;
  
  return markdown;
}

/**
 * Generates a highly interactive, self-contained HTML document (.html)
 * containing full statistics, risk charts, and a detailed responsive systems report.
 */
export function exportAsHtmlReport(architecture: Architecture): string {
  const dateStr = new Date().toLocaleString();
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>System Design Spec: ${architecture.name}</title>
  <style>
    :root {
      --bg: #030712;
      --card-bg: #0b0f19;
      --border: #1e293b;
      --text: #f3f4f6;
      --text-muted: #9ca3af;
      --primary: #3b82f6;
      --success: #10b981;
      --warning: #f59e0b;
      --danger: #ef4444;
      --purple: #8b5cf6;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      line-height: 1.5;
      padding: 40px 20px;
    }
    .container { max-width: 1100px; margin: 0 auto; }
    header {
      border-bottom: 1px solid var(--border);
      padding-bottom: 24px;
      margin-bottom: 32px;
    }
    .eyebrow {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: var(--primary);
      font-weight: 700;
      margin-bottom: 8px;
    }
    h1 { font-size: 32px; font-weight: 800; tracking: -0.025em; margin-bottom: 8px; color: #fff; }
    .desc { font-size: 15px; color: var(--text-muted); margin-bottom: 16px; }
    .meta-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-top: 16px; }
    .meta-card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px; padding: 16px; }
    .meta-label { font-size: 11px; text-transform: uppercase; color: var(--text-muted); font-weight: 600; }
    .meta-value { font-size: 20px; font-weight: 700; color: #fff; margin-top: 4px; }
    
    .section-title { font-size: 20px; font-weight: 700; margin: 40px 0 16px 0; border-bottom: 1px solid var(--border); padding-bottom: 8px; color: #fff; display: flex; alignItems: center; gap: 8px; }
    
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { text-align: left; background-color: rgba(15, 23, 42, 0.6); padding: 12px 16px; font-size: 12px; font-weight: 600; text-transform: uppercase; color: var(--text-muted); border-bottom: 1px solid var(--border); }
    td { padding: 12px 16px; font-size: 13px; border-bottom: 1px solid var(--border); color: var(--text); }
    tr:hover { background-color: rgba(255, 255, 255, 0.02); }
    
    .status-badge { display: inline-flex; align-items: center; gap: 6px; font-size: 11px; font-weight: 600; padding: 2px 8px; border-radius: 99px; text-transform: uppercase; }
    .status-badge.healthy { background: rgba(16, 185, 129, 0.1); color: var(--success); border: 1px solid rgba(16, 185, 129, 0.2); }
    .status-badge.failed { background: rgba(239, 68, 68, 0.1); color: var(--danger); border: 1px solid rgba(239, 68, 68, 0.2); }
    .status-badge.degraded { background: rgba(245, 158, 11, 0.1); color: var(--warning); border: 1px solid rgba(245, 158, 11, 0.2); }
    
    .badge { display: inline-block; font-size: 10px; font-family: monospace; padding: 2px 6px; border-radius: 4px; background: rgba(255,255,255,0.08); color: var(--text); }
    
    .list-card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 16px; }
    .list-item { display: flex; gap: 12px; margin-bottom: 12px; font-size: 14px; }
    .list-item:last-child { margin-bottom: 0; }
    .list-icon { color: var(--primary); font-weight: bold; }
    
    .danger-item .list-icon { color: var(--danger); }
    .success-item .list-icon { color: var(--success); }
    
    .footer { text-align: center; margin-top: 60px; padding-top: 20px; border-top: 1px solid var(--border); font-size: 12px; color: var(--text-muted); }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="eyebrow">SYNTHARCHITECTURE SPECIFICATION REPORT</div>
      <h1>${architecture.name}</h1>
      <p class="desc">${architecture.description}</p>
      
      <div class="meta-grid">
        <div class="meta-card">
          <div class="meta-label">Total Components</div>
          <div class="meta-value">${architecture.nodes.length}</div>
        </div>
        <div class="meta-card">
          <div class="meta-label">Total Routes</div>
          <div class="meta-value">${architecture.edges.length}</div>
        </div>
        <div class="meta-card">
          <div class="meta-label">Design Peak Load</div>
          <div class="meta-value">${Math.round(architecture.estimatedTraffic.requestsPerSecond * architecture.estimatedTraffic.peakMultiplier).toLocaleString()} RPS</div>
        </div>
        <div class="meta-card">
          <div class="meta-label">Export Timestamp</div>
          <div class="meta-value" style="font-size:12px; padding-top:6px;">${dateStr}</div>
        </div>
      </div>
    </header>

    <div class="section-title">📦 Active Nodes Inventory</div>
    <div style="overflow-x: auto;">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Region</th>
            <th>Capacity</th>
            <th>Replicas</th>
            <th>Nominal Latency</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${architecture.nodes.map(n => `
            <tr>
              <td><strong>${n.name}</strong><br><span style="font-size:11px; color:var(--text-muted); font-family:monospace;">${n.id}</span></td>
              <td><span class="badge">${n.type}</span></td>
              <td>${n.region}</td>
              <td>${n.capacity.toLocaleString()} RPS</td>
              <td>${n.replicas}x</td>
              <td>${n.latencyMs}ms</td>
              <td><span class="status-badge ${n.status}">${n.status}</span></td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>

    <div class="section-title">🔌 Protocol Connection Map</div>
    <div style="overflow-x: auto;">
      <table>
        <thead>
          <tr>
            <th>Route ID</th>
            <th>Source</th>
            <th>Target</th>
            <th>Protocol</th>
            <th>Weight</th>
            <th>Latency</th>
            <th>State</th>
          </tr>
        </thead>
        <tbody>
          ${architecture.edges.map(e => {
            const src = architecture.nodes.find(n => n.id === e.source)?.name || e.source;
            const tgt = architecture.nodes.find(n => n.id === e.target)?.name || e.target;
            return `
              <tr>
                <td style="font-family:monospace; font-weight:600;">${e.id}</td>
                <td>${src}</td>
                <td>→ ${tgt}</td>
                <td><span class="badge" style="background-color:rgba(59,130,246,0.1); color:var(--primary);">${e.protocol}</span></td>
                <td>${e.trafficPercentage}%</td>
                <td>${e.latencyMs}ms</td>
                <td><span style="font-size:12px; font-weight:600; color:${e.active ? 'var(--success)' : 'var(--text-muted)'}">${e.active ? 'Active' : 'Backup Standby'}</span></td>
              </tr>
            `;
          }).join('')}
        </tbody>
      </table>
    </div>

    <div class="section-title">💡 System Assumptions</div>
    <div class="list-card">
      ${architecture.assumptions.map(a => `
        <div class="list-item success-item">
          <span class="list-icon">✔</span>
          <span>${a}</span>
        </div>
      `).join('')}
    </div>

    <div class="section-title">🚨 Reliability & Risk Register</div>
    <div class="list-card">
      ${architecture.risks.map(r => `
        <div class="list-item danger-item">
          <span class="list-icon">⚠</span>
          <span>${r}</span>
        </div>
      `).join('')}
    </div>

    <div class="section-title">🛠 Optimization Recommendations</div>
    <div class="list-card">
      ${architecture.recommendations.map(r => `
        <div class="list-item">
          <span class="list-icon">➔</span>
          <span>${r}</span>
        </div>
      `).join('')}
    </div>

    <div class="footer">
      Generated by SynthArchitecture Studio • Dedicated Systems Evaluation Console
    </div>
  </div>
</body>
</html>`;
}

/**
 * Generates a gorgeous, self-contained SVG representation of the topology map,
 * complete with curved bezier paths, high-tech glow, gradients, status indicators, and grid background.
 */
export function exportAsSvg(architecture: Architecture): string {
  // Find layout bounds to set clean viewBox
  let minX = Infinity;
  let maxX = -Infinity;
  let minY = Infinity;
  let maxY = -Infinity;
  
  const nodeWidth = 270;
  const nodeHeight = 160;

  const resolvedCoords = architecture.nodes.map((node, index) => {
    const coords = getNodeCoords(node, index);
    minX = Math.min(minX, coords.x);
    maxX = Math.max(maxX, coords.x + nodeWidth);
    minY = Math.min(minY, coords.y);
    maxY = Math.max(maxY, coords.y + nodeHeight);
    return {
      node,
      ...coords
    };
  });

  if (minX === Infinity) { minX = 0; maxX = 1200; minY = 0; maxY = 600; }

  // Add standard responsive padding around the bounding box
  const paddingLeft = 100;
  const paddingTop = 100;
  const paddingRight = 100;
  const paddingBottom = 100;

  const viewWidth = Math.max(1200, (maxX - minX) + paddingLeft + paddingRight);
  const viewHeight = Math.max(700, (maxY - minY) + paddingTop + paddingBottom);

  const startX = minX - paddingLeft;
  const startY = minY - paddingTop;

  let svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="${startX} ${startY} ${viewWidth} ${viewHeight}">
  <style>
    .bg { fill: #020617; }
    .grid { stroke: rgba(30, 41, 59, 0.4); stroke-width: 1; }
    .node-rect { fill: #0b1329; stroke: #1e293b; stroke-width: 1.5; rx: 12px; }
    .node-rect-selected { stroke: #3b82f6; stroke-width: 2.5; }
    .node-rect-failed { stroke: #ef4444; stroke-width: 2; }
    .node-text-title { fill: #ffffff; font-family: 'Inter', sans-serif; font-size: 13px; font-weight: 700; }
    .node-text-meta { fill: #94a3b8; font-family: 'Inter', sans-serif; font-size: 10px; font-weight: 500; }
    .node-text-desc { fill: #cbd5e1; font-family: 'Inter', sans-serif; font-size: 10px; }
    .node-text-metric { fill: #64748b; font-family: 'Inter', sans-serif; font-size: 10px; font-weight: 600; }
    .node-text-metric b { fill: #e2e8f0; }
    .badge { rx: 4px; }
    .badge-text { fill: #94a3b8; font-family: monospace; font-size: 9px; font-weight: bold; text-anchor: middle; }
    .status-healthy { fill: #10b981; }
    .status-failed { fill: #ef4444; }
    .status-degraded { fill: #f59e0b; }
    .edge-line { fill: none; stroke: #5b99ff; stroke-width: 2.5; }
    .edge-line-backup { stroke: #c787ff; stroke-dasharray: 6,5; }
    .edge-glow { fill: none; stroke: #5b99ff; stroke-width: 5; opacity: 0.35; filter: url(#blur-filter); }
    .edge-glow-backup { stroke: #c787ff; }
    .edge-protocol { fill: #0f172a; stroke: #1e293b; stroke-width: 1; rx: 4px; }
    .edge-protocol-text { fill: #38bdf8; font-family: monospace; font-size: 9px; font-weight: 700; text-anchor: middle; }
    .title-banner { fill: #ffffff; font-family: 'Inter', sans-serif; font-size: 24px; font-weight: 800; letter-spacing: -0.02em; }
    .subtitle-banner { fill: #64748b; font-family: 'Inter', sans-serif; font-size: 12px; }
  </style>

  <defs>
    <!-- Grid Pattern -->
    <pattern id="gridPattern" width="40" height="40" patternUnits="userSpaceOnUse">
      <path d="M 40 0 L 0 0 0 40" fill="none" class="grid" />
    </pattern>
    
    <!-- Linear Gradients -->
    <linearGradient id="grad-healthy" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#0b1528" />
      <stop offset="100%" stop-color="#050914" />
    </linearGradient>
    <linearGradient id="grad-failed" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#1c0d12" />
      <stop offset="100%" stop-color="#0a0507" />
    </linearGradient>
    <linearGradient id="grad-degraded" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#1c160d" />
      <stop offset="100%" stop-color="#0a0805" />
    </linearGradient>

    <!-- Node Glow Shadow -->
    <filter id="shadow-glow" x="-10%" y="-10%" width="120%" height="120%">
      <feDropShadow dx="0" dy="8" stdDeviation="12" flood-color="#000000" flood-opacity="0.65" />
      <feDropShadow dx="0" dy="0" stdDeviation="4" flood-color="#3b82f6" flood-opacity="0.15" />
    </filter>

    <filter id="blur-filter" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="3" />
    </filter>

    <!-- Edge Markers -->
    <marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 0.5 L 10 5 L 0 9.5 z" fill="#70beff" />
    </marker>
    <marker id="arrow-backup" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 0.5 L 10 5 L 0 9.5 z" fill="#c787ff" />
    </marker>
  </defs>

  <!-- Background and Grid -->
  <rect x="${startX}" y="${startY}" width="${viewWidth}" height="${viewHeight}" class="bg" />
  <rect x="${startX}" y="${startY}" width="${viewWidth}" height="${viewHeight}" fill="url(#gridPattern)" />

  <!-- Title & Subtitle Banner -->
  <text x="${startX + paddingLeft}" y="${startY + 60}" class="title-banner">${architecture.name}</text>
  <text x="${startX + paddingLeft}" y="${startY + 82}" class="subtitle-banner">SynthArchitecture topology snapshot • Design spec: ${architecture.nodes.length} elements</text>
`;

  // DRAW EDGES FIRST SO THEY ARE IN THE BACKGROUND
  architecture.edges.forEach((edge) => {
    const sourceResolved = resolvedCoords.find(n => n.node.id === edge.source);
    const targetResolved = resolvedCoords.find(n => n.node.id === edge.target);

    if (sourceResolved && targetResolved) {
      const x1 = sourceResolved.x + nodeWidth;
      const y1 = sourceResolved.y + nodeHeight / 2;
      const x2 = targetResolved.x;
      const y2 = targetResolved.y + nodeHeight / 2;

      const dx = x2 - x1;
      // Draw smooth, high-fidelity bezier curves
      const pathStr = `M ${x1} ${y1} C ${x1 + dx * 0.45} ${y1}, ${x2 - dx * 0.45} ${y2}, ${x2} ${y2}`;
      
      const isBackup = edge.backup;
      const glowClass = isBackup ? "edge-glow edge-glow-backup" : "edge-glow";
      const lineClass = isBackup ? "edge-line edge-line-backup" : "edge-line";
      const marker = isBackup ? "url(#arrow-backup)" : "url(#arrow)";

      if (edge.active) {
        svg += `  <path d="${pathStr}" class="${glowClass}" />\n`;
      }
      svg += `  <path d="${pathStr}" class="${lineClass}" marker-end="${marker}" style="opacity: ${edge.active ? 1 : 0.4};" />\n`;

      // Draw protocol label on the midpoint
      const midX = x1 + dx / 2;
      // Compute bezier point at t=0.5
      const midY = 0.125 * y1 + 0.375 * y1 + 0.375 * y2 + 0.125 * y2; // Approx vertical center
      const labelW = 44;
      const labelH = 16;
      svg += `  <g transform="translate(${midX - labelW/2}, ${midY - labelH/2})" style="opacity: ${edge.active ? 1 : 0.6};">
    <rect width="${labelW}" height="${labelH}" class="edge-protocol" />
    <text x="${labelW/2}" y="11" class="edge-protocol-text">${edge.protocol}</text>
  </g>\n`;
    }
  });

  // DRAW NODES ON TOP
  resolvedCoords.forEach(({ node, x, y }) => {
    const isFailed = node.status === 'failed';
    const isDegraded = node.status === 'degraded';
    const gradId = isFailed ? "url(#grad-failed)" : isDegraded ? "url(#grad-degraded)" : "url(#grad-healthy)";
    
    const strokeClass = isFailed ? "node-rect node-rect-failed" : "node-rect";
    const statusClass = isFailed ? "status-failed" : isDegraded ? "status-degraded" : "status-healthy";
    
    const utilization = Math.round((node.currentLoad / Math.max(node.capacity, 1)) * 100);
    const desc = node.type === 'database' ? 'Transactional ledger data store.' : node.type === 'gateway' ? 'Ingress router & auth.' : 'Capacity for active traffic.';

    svg += `  <!-- Node: ${node.name} -->
  <g transform="translate(${x}, ${y})" filter="url(#shadow-glow)">
    <rect width="${nodeWidth}" height="${nodeHeight}" class="${strokeClass}" fill="${gradId}" />
    
    <!-- Header Icon Tag -->
    <rect x="14" y="14" width="22" height="18" rx="3" fill="#1e293b" />
    <text x="25" y="26" class="badge-text">${node.type.slice(0,2).toUpperCase()}</text>

    <!-- Node Title -->
    <text x="44" y="22" class="node-text-title">${node.name.length > 28 ? node.name.slice(0, 26) + '...' : node.name}</text>
    <text x="44" y="34" class="node-text-meta">${node.region} · ${node.type.toUpperCase()}</text>

    <!-- Status Indicator -->
    <circle cx="${nodeWidth - 24}" cy="24" r="5" class="${statusClass}" />
    
    <!-- Description text -->
    <text x="14" y="66" class="node-text-desc">${desc}</text>
    
    <line x1="14" y1="84" x2="${nodeWidth - 14}" y2="84" stroke="rgba(30, 41, 59, 0.4)" stroke-width="1" />

    <!-- Metrics -->
    <text x="14" y="112" class="node-text-metric">Capacity: <tspan fill="#e2e8f0" font-weight="bold">${node.capacity.toLocaleString()}</tspan></text>
    <text x="14" y="128" class="node-text-metric">Load: <tspan fill="#e2e8f0" font-weight="bold">${node.currentLoad.toLocaleString()} (${utilization}%)</tspan></text>
    <text x="${nodeWidth / 2 + 10}" y="112" class="node-text-metric">Latency: <tspan fill="#e2e8f0" font-weight="bold">${node.latencyMs}ms</tspan></text>
    <text x="${nodeWidth / 2 + 10}" y="128" class="node-text-metric">Replicas: <tspan fill="#e2e8f0" font-weight="bold">${node.replicas}x</tspan></text>
  </g>\n`;
  });

  svg += `</svg>`;
  return svg;
}
